#!/usr/bin/python3
def raise_exception():
    num = 4 + 'a'
